# Generated by Django 6.0.2 on 2026-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='day_and_time',
        ),
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], default='Breakfast', max_length=20),
        ),
    ]
