# Generated by Django 6.0.2 on 2026-03-22 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0009_delete_messbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('verification_id', models.UUIDField(unique=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
