# Generated by Django 6.0.2 on 2026-03-27 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0015_alter_mybooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooking',
            name='qr_code_id',
        ),
        migrations.RemoveField(
            model_name='qrdatabase',
            name='item',
        ),
        migrations.AddField(
            model_name='mybooking',
            name='qr_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to='Backend_App.qrdatabase'),
        ),
        migrations.AddField(
            model_name='qrdatabase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
